### ISSUE TITLE
The link of the "installation and configuration Redis" tutorial in README.md leads to 403 page

### ISSUE THREAD

**Issue by kanenas** [pressjitsu/pj-object-cache-red#2]
In **README.md**:

1. Install and configure Redis. There is a good tutorial [here](http://www.saltwebsites.com/2012/install-redis-245-service-centos-6).

This link http://www.saltwebsites.com/2012/install-redis-245-service-centos-6 leads to a **403 (Forbidden)** page.

**Comment by soulseekah** [comment]
Thanks. Any good ideas what to substitute it for?

**Comment by logicalphase** [comment]
Try
https://www.digitalocean.com/community/tutorials/how-to-install-secure-redis-centos-7
which covers all the important steps.

**Comment by soulseekah** [comment]
Cool. What about Debian-based? We can add one as well?

Upd: nvm, they have the other versions as well.

**Comment by logicalphase** [comment]
There's also
https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-debian-9.
Serverpilot has a good one for Ubuntu Server.

**Comment by soulseekah** [comment]
Updated. Thanks.
