### ISSUE TITLE
[info] - comparison with wp-redis

### ISSUE THREAD

**Issue by wkhayrattee** [pressjitsu/pj-object-cache-red#21]
Hello,
I'm curious as to how this compares with [wp-redis](https://wordpress.org/plugins/wp-redis)

thank you.

**Comment by dingman** [comment]
You could test it and find out....

**Comment by soulseekah** [comment]
https://github.com/pressjitsu/pj-object-cache-red#why-is-this-fork-better

To date there are no known `mGet` implementations for Redis wp_cache backends.
