### ISSUE TITLE
wp-admin caching

### ISSUE THREAD

**Issue by dingman** [pressjitsu/pj-object-cache-red#22]
I looked at the code, but didn't see anything specifically for it.

Is there any object caching for the backend of the dashboard, to speed up the experience?

**Comment by soulseekah** [comment]
Yes. Object cache implementations provide a backend for `wp_cache_*` functions (`wp_cache_get`, etc.). These calls to the Object Cache API are used by WordPress throughout the core. This includes the admin.

There are nuances regarding "speeding up", though. You need to always benchmark and measure. In some setups Object Caching does more harm than good. So compare, compare, compare. Use the Debug Bar plugin which shows Object Cache hit rates, performance metrics, etc.

**Comment by dingman** [comment]
Thank you!

Absolutely love the object+page caching combo, thank you SO much for these fantastic products.
