### ISSUE TITLE
Add a way to disable caching

### ISSUE THREAD

**Issue by grappler** [pressjitsu/pj-object-cache-red#23]
It would be nice to have a way to disable the redis caching without needing to delete the file.

We have previously used a constant `WP_REDIS_DISABLED` to disable the redis cache.

Would this be something that you would be willing to support?

**Comment by soulseekah** [comment]
This is a good suggestion. Thank you.

What's the other plugin you used? I don't think this is a standard constant, and I'm a bit weary of conflicts with non-object caching plugins (like Redis-backed Page caches), perhaps?

Is there a better core way to disable object cache altogether?

**Comment by grappler** [comment]
We previously used https://wordpress.org/plugins/redis-cache/ which had this constant.

**Comment by soulseekah** [comment]
You can send us a patch, I think we can implement this.
