### ISSUE TITLE
Query Monitor compatibility?

### ISSUE THREAD

**Issue by lkraav** [pressjitsu/pj-object-cache-red#3]
Current QM output:

Object Cache
nan% hit rate (0 hits, 0 misses)
External object cache in use

I would expect QM to be able to collect numbers correctly, it's been able to for other object cache implementations.

**Comment by soulseekah** [comment]
We'll think about providing statistics when Query Monitor is on. Thank you for your suggestion.

**Comment by lkraav** [comment]
It's not that I look at that panel specifically very often, but it's the easiest way to achieve confirmation "things are working correctly".

**Comment by logicalphase** [comment]
We use the CLI command: 

$ redis-cli monitor 

Or am I missing something (which happens more often than I'd like to admit)?

**Comment by lkraav** [comment]
PS this cache stats mismatch also causes QM to spew into error log on every request:

`[27-Dec-2018 16:21:07 UTC] PHP Warning:  Division by zero in /home/warmpress/wp-content/plugins/query-monitor.git/collectors/cache.php on line 70`

https://github.com/johnbillion/query-monitor/blob/master/collectors/cache.php#L70

**Comment by ocean90** [comment]
Created a PR #10 which implements the missing counters.
