### ISSUE TITLE
Admin UI possbility?

### ISSUE THREAD

**Issue by michaeledi** [pressjitsu/pj-object-cache-red#30]
Really appreciate the awesome plugin that takes object caching a step further! But as a rookie of redis, I feel quite uncertain if it works properly because the installation is quite unnoticable :D It's a good thing for developers, but is it possible to add an admin panel like Till Krüss's redis object plugin? It shows the connection status and some basic info that helps.

Thanks!

**Comment by soulseekah** [comment]
Ola Edi,

I'm pretty sure that the plugin integrates well with Debug Bar https://wordpress.org/plugins/debug-bar/ in the Object Cache tab. As speed freaks we will not weigh our plugin down with a UI :)

G.
