### ISSUE TITLE
How can I tell if is working?

### ISSUE THREAD

**Issue by steelliberty** [pressjitsu/pj-object-cache-red#31]
Hi -- I just replaced the redis-object cache in wordpress with pr-object-cache-red.  I removed the plugin and put your object-cache.php in the wp-content directory.   How will I know if it is working ?  How will the cache be flushed -- if needed?  

Thank you. -- Jack

**Comment by soulseekah** [comment]
You can enable the Debug Bar plugin and check the Object Cache stats.

wp cache flush via WP-CLI will let you flush your caches.

Hope this helps.

**Comment by steelliberty** [comment]
thank you, soulseekah:  I installed debug_bar (and activated wp_debug in config) and I see error messages -- which is helpful but nothing regarding the cache -- is does that indicate that it is not working ?

**Comment by soulseekah** [comment]
As per https://wordpress.org/plugins/debug-bar/ you need to click on the Debug button at the top of your page and select Object Cache.

**Comment by steelliberty** [comment]
Unfortunately Object Cache does not appear on the left or elsewhere .. redis-server is running and I restarted it -- object-cache.php is in the wp-content directory with r only permissions and the server user www-data

**Comment by steelliberty** [comment]
![Screen Shot 2020-10-23 at 10 22 14 AM](https://user-images.githubusercontent.com/5113718/97015816-03156980-151a-11eb-9990-923fecbda72d.jpg)

Thank you for the help -- i really would like the cache to be in operation. Running it on a buddyboss site with over 6000 users .. and the site is crawling .
